Repository NPGW/npgw-ui-test, pull requests merged in 2025-04, with the labels that each got.

#173 Feature: add user role
  src/test/java/xyz/npgw/test/common/ProjectUtils.java
  src/test/java/xyz/npgw/test/common/UserRole.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/page/AboutBlankPage.java
  src/test/java/xyz/npgw/test/page/base/BasePageWithHeader.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
Labels: Feature

#166 [ATC_00.011.01] Unauthenticated users are automatically redirected to the 'Login page'
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
  src/test/java/xyz/npgw/test/testdata/TestDataProvider.java
Labels: Login

#180 Fix: remove double wrapping
  src/test/java/xyz/npgw/test/page/base/BasePageWithHeader.java
  src/test/java/xyz/npgw/test/page/component/Element.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
  src/test/java/xyz/npgw/test/run/SystemAdministrationPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactor, Fix

#190 [ATC_10.002.02] Verify that the placeholder text for each field is correct.
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: ATC, SA / Companies and business units

#192 [ATC_10.002.03] Verify that error message is shown for company name is shorter than 4 or longer than 100 characters.
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/testdata/TestDataProvider.java
Labels: ATC, SA / Companies and business units

#207 [ATC_10.002.04] 'Create' button is disabled when required fields are not filled.
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/testdata/TestDataProvider.java
Labels: ATC, SA / Companies and business units

#205 Refactor: remove useless properties
  pom.xml
Labels: Refactor

#185 [ATC_10.002.01] Verify that clicking the Close button successfully closes the 'Add Company' dialog.
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: ATC, SA / Companies and business units

#208 Feature: add lombok
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/SystemAdministrationWithTableBasePage.java
  src/test/java/xyz/npgw/test/page/systemadministration/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
Labels: Feature

#216 [ATC_10.002.05] Error is displayed when trying to create a company with special characters in the name.
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/testdata/TestDataProvider.java
Labels: ATC, SA / Companies and business units

#222 Refactor constants according to requirements
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/PlaywrightOptions.java
  src/test/java/xyz/npgw/test/common/ProjectUtils.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
  src/test/java/xyz/npgw/test/testdata/Constants.java
Labels: Refactor

#230 Add tests #227 and #228
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: ATC

#225 [ATC_10.002.06] Company can be added by filling out required fields , [ATC_10.002.06] Added company appears in the 'Select company' dropdown list
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: ATC, SA / Companies and business units

#234 Add ATC_11.003.00 При нажатии на поле "Status" выпадает список c опциями "ALL/Active/Inactive"
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/systemadministration/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/resources/allure.properties
Labels: ATC, SA / Acquirers

#236 ATC_11.003.00 При нажатии на поле "Status" выпадает список c опциями "ALL/Active/Inactive"
  .gitignore
  src/test/java/xyz/npgw/test/page/systemadministration/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: ATC

#237 Refactor: basetest
  .github/workflows/ci.yml
  src/test/java/xyz/npgw/test/common/ApiContextUtils.java
  src/test/java/xyz/npgw/test/common/BrowserFactory.java
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/ProjectUtils.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
Labels: Refactor

#212 [ATC_01.000.00][ATC_01.002.00][ATC_01.003.00]
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/component/HeaderComponent.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: ATC

#247 [ATC_10.002.11] Validates successful company creation and correct field persistence (e2e).
  src/test/java/xyz/npgw/test/common/dto/Company.java
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/utils/CompanyUtils.java
  src/test/resources/jsonfiles/company.json
Labels: ATC, SA / Companies and business units

#262 [ATC_10.002.12] Error message when trying to create a company with invalid length and special characters.
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/resources/jsonfiles/company.json
Labels: ATC, System / Companies and business units

#217 Refactor: change properties
  .github/workflows/ci.yml
  .gitignore
  config/.env.TEMPLATE
  src/test/java/xyz/npgw/test/common/PlaywrightOptions.java
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/resources/access.properties.TEMPLATE
  src/test/resources/browser.properties.TEMPLATE
Labels: Refactor, Feature

#254 Allure annotations refactoring according to the Feature Matrix
  src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/testdata/CreatorCompanyWithRandomName.java
Labels: documentation, Refactor

#264 [ATC-06.015.00] Choose amount popup functionality #263
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/component/HeaderComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#267 [ATC_10.007.00] Edit and save company info
  src/test/java/xyz/npgw/test/common/dto/CompanyUtils.java
  src/test/java/xyz/npgw/test/common/dto/CreatorCompanyWithRandomName.java
  src/test/java/xyz/npgw/test/page/dialog/EditAcquirersDialog.java
  src/test/java/xyz/npgw/test/page/dialog/EditCompanyDialog.java
  src/test/java/xyz/npgw/test/page/systemadministration/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
Labels: ATC

#270 Refactor: change structure
  src/test/java/xyz/npgw/test/common/util/Company.java
  src/test/java/xyz/npgw/test/common/util/CompanyUtils.java
  src/test/java/xyz/npgw/test/common/util/CreatorCompanyWithRandomName.java
  src/test/java/xyz/npgw/test/component/BaseComponent.java
  src/test/java/xyz/npgw/test/component/HeaderComponent.java
  src/test/java/xyz/npgw/test/component/SystemMenuComponent.java
  src/test/java/xyz/npgw/test/component/TableComponent.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/BaseWithHeaderAndTablePage.java
  src/test/java/xyz/npgw/test/page/base/BaseWithHeaderPage.java
  src/test/java/xyz/npgw/test/page/base/SystemAdministrationBasePage.java
  src/test/java/xyz/npgw/test/page/base/SystemAdministrationWithTableBasePage.java
  src/test/java/xyz/npgw/test/page/dialog/AddAcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/dialog/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/EditCompanyDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/SystemBasePage.java
  src/test/java/xyz/npgw/test/page/system/SystemWithTableBasePage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactor

#271 Feature: add traits
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/UserRole.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/component/TableComponent.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/BaseHeaderPage.java
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/base/BaseWithHeaderAndTablePage.java
  src/test/java/xyz/npgw/test/page/base/BaseWithHeaderPage.java
  src/test/java/xyz/npgw/test/page/base/trait/BaseTrait.java
  src/test/java/xyz/npgw/test/page/base/trait/HeaderTrait.java
  src/test/java/xyz/npgw/test/page/base/trait/SystemMenuTrait.java
  src/test/java/xyz/npgw/test/page/base/trait/TableTrait.java
  src/test/java/xyz/npgw/test/page/dialog/AcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/AddAcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/page/dialog/CompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/EditAcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/EditCompanyDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/SystemBasePage.java
  src/test/java/xyz/npgw/test/page/system/SystemWithTableBasePage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Feature

#274 Feature: add defaultTimeout property with default 5 seconds instead o…
  src/test/java/xyz/npgw/test/common/BrowserFactory.java
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
Labels: Feature

#277 Refactor PR #247
  src/test/java/xyz/npgw/test/common/util/Company.java
  src/test/java/xyz/npgw/test/common/util/CompanyUtils.java
  src/test/java/xyz/npgw/test/page/dialog/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/resources/jsonfiles/company.json
Labels: Refactor

#279 Refactor: transfer duplicate locators to CompanyDialog class
  src/test/java/xyz/npgw/test/page/dialog/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/CompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/EditCompanyDialog.java
Labels: Refactor

#278 Refactor: rewrite of CreatorCompanyWithRandomName
  src/test/java/xyz/npgw/test/common/BrowserFactory.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/util/Company.java
  src/test/java/xyz/npgw/test/common/util/CreatorCompanyWithRandomName.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
Labels: Refactor

#280 Refactor: rewrite company dialog with generics
  src/test/java/xyz/npgw/test/page/dialog/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/CompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/EditCompanyDialog.java
Labels: Refactor

#294 Fix: ignore testFilterAcquirersByStatus after uodate
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: Fix

#296 Fix: ignore AddAcquirerDialogTest class
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
Labels: Fix

#286 ATC_12.002.00 | ATC_12.002.02
  src/test/java/xyz/npgw/test/component/SystemMenuComponent.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
Labels: ATC, System / Gateway

#301 Refactor: components moved to their respective usage places
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/BaseComponent.java
  src/test/java/xyz/npgw/test/page/base/BaseHeaderPage.java
  src/test/java/xyz/npgw/test/page/base/BaseTrait.java
  src/test/java/xyz/npgw/test/page/base/trait/SystemMenuTrait.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/page/common/HeaderPage.java
  src/test/java/xyz/npgw/test/page/common/HeaderTrait.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/page/common/TableTrait.java
  src/test/java/xyz/npgw/test/page/dialog/company/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/CompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/EditCompanyDialog.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/MenuComponent.java
  src/test/java/xyz/npgw/test/page/system/MenuTrait.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
Labels: Refactor

#299 [ATC_09.002.05] Add users with roles [SUPER, ADMIN, USER] as super admin
  src/test/java/xyz/npgw/test/common/TestUtils.java
  src/test/java/xyz/npgw/test/common/UserRole.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/util/Company.java
  src/test/java/xyz/npgw/test/common/util/User.java
  src/test/java/xyz/npgw/test/page/dialog/AddUserDialog.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: System / Team, ATC

#297 [AT-10.003.06] Validates successful business unit addition to company (E2E test).
  src/test/java/xyz/npgw/test/common/util/Merchant.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: ATC, System / Companies and BU

#302 [ATC_01.006.00] Check change the password in the user menu.
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
Labels: ATC, Header

#312 Generic adding to the BaseDialog to find the ReturnPage after clickClosebutton
  src/test/java/xyz/npgw/test/page/dialog/AddUserDialog.java
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/CompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
Labels: Refactor, System / Acquirers, System / Companies and BU

#314 [ATC_12.003.01] System administration > Gateway > Select company > Business units list
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
Labels: ATC, System / Gateway

#313 [ATC_06.015.01] Filtering transactions by Amount
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#310 Fix: suppress unchecked warnings
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/CompanyDialog.java
Labels: Fix

#316 testEditCompanyInfoAndSave #266 - bug gone
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
Labels: Refactoring

#320 [ATC_06.002.01] Filtering transactions by Currency
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#317 BaseDialog etc.: refactoring, generics
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/CompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
Labels: Refactoring

#325 test got moved to diff page
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
Labels: Refactoring

#327 ATC_11.001.03 Selecting already selected Timezone does not change the value
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
Labels: ATC, System / Acquirers

#329 UnIgnore AcquirersPageTest
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: Refactoring

#328 Full behavior of clickSystemAdministrationLink()
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
Labels: Refactoring

#338 System Tabs and MenuComponent Refactoring
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/MenuComponent.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
Labels: Refactoring

#339 RF testAddUser
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java
  src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#348 REF [ATC_12.003.01] System administration > Gateway > Select company > Business units list
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
Labels: Refactoring, System / Gateway

#341 [ATC-06.000.01] Error message is displayed when start date is after end date.
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Dashboard, ATC

#169 Feature: add ATC issue template
  .github/ISSUE_TEMPLATE/00-ATC.md
Labels: Feature

#292 New test public void testAddNewMerchants() is added
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/Company.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: System / Companies and BU

#350 [ATC_06.014.00] Transactions table headers and Visible columns from Settings - presence, spelling and order
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#368 System -> Acquirers -> testAddAcquirerFormOpensWithCorrectHeaderAndFieldsAndClosesCorrectly fixing after update
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
Labels: Fix, System / Acquirers

#372 System -> Acquirers -> testVisibilityHeaderAndAcquirersList fixing after update
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: Fix, System / Acquirers

#370 System -> Acquirers -> testVisibilityAcquirersListControlTab fixing after update
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: Fix, System / Acquirers

#375 System -> Acquirers -> testRetainStatusWhenReSelectingSameOption fixing after update
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: Fix, System / Acquirers

#359 [ATC_06.007.00] Transactions -> Settings -> Check/Uncheck Visible columns in the Settings and verify table columnheaders
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#365 Transactions -> testChooseAmountPopUp - fixing after update
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, Fix

#381 [ATC_11.000.03] Verify that the "Rows per page" dropdown has the following options: 10, 25, 50, 100.
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: ATC, System / Acquirers

#379 test works
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: System / Acquirers

#383 [ATC_11.000.04] SA/Aquirer > Verify Selecting "Rows Per Page" Option Updates the Field Value
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: ATC, System / Acquirers

#389 Fix tests according updates in AddCompanyTest
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: Fix

#397 Edit Amount
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#398 Reset Amount Values
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#392 System -> Team-> testAddUser fixing
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: System / Team, Fix

#393 Add DataRangePickerComponent
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/DateRangePickerComponent.java
  src/test/java/xyz/npgw/test/page/common/DateRangePickerTrait.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring

#402 System -> Acquirers ->testFilterAcquirersByStatus fixing after update #401
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: Fix, System / Acquirers

#404 [ATC-02.001.00] Dashboard | Error message is displayed when start date is after end date
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
Labels: Dashboard, ATC

#408 Add select company component
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyTrait.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#394 [ATC_11.000.05] Verify Selecting "Rows Per Page" Option Updates the Field Value
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: ATC, System / Acquirers

#390 [ATC_10.008.00] Verify 'Edit Business Unit' window header title
  src/test/java/xyz/npgw/test/page/dialog/merchant/EditBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: ATC, System / Companies and BU

#399 Business unit refactoring due to new UI changes
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: Refactoring

#414 Feature: add docker-compose*.yml
  .gitignore
Labels: Feature

#417 [ATC_06.006.00] The presence of the dropdown options export table data to file
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#415 Fix: encode space as %20
  src/test/java/xyz/npgw/test/common/TestUtils.java
Labels: Fix

#420 Refactor after update of EditCompanyDialogTest
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring, System / Companies and BU
