Repository NPGW/npgw-ui-test, pull requests merged in 2025-06, with the labels that each got.

#675 Increase speed
  src/test/java/xyz/npgw/test/common/entity/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/entity/Company.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/common/DateRangePickerComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectAcquirerComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectDateRangeComponent.java
  src/test/java/xyz/npgw/test/page/common/trait/DateRangePickerTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/SelectDateRangeTrait.java
  src/test/java/xyz/npgw/test/page/dialog/reports/ReportsParametersDialog.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Feature

#679 [ATC-06.012.01] Transactions > Status > Filter > testDisplayAllFilteredByStatusRows
  src/test/java/xyz/npgw/test/page/common/SelectDateRangeComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectStatusComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#689 [ATC-06.000.02] Filtering transactions by Date range
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#682 [ATC-06.002.03] Transactions > Currency > Filter > testTableDisplayWhenCurrencyFilterAppliedWhileOnLastPage
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#698 Refactor delete company
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/entity/Acquirer.java
  src/test/java/xyz/npgw/test/common/entity/Address.java
  src/test/java/xyz/npgw/test/common/entity/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/entity/Company.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/common/SelectStatusComponent.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
Labels: Refactoring

#695 Refactoring BaseTableComponent
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, Fix

#688 Change order
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/CleanupUtils.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/common/SelectAcquirerComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring

#719 Correct transaction summary is displayed on Dashboard page
  src/test/java/xyz/npgw/test/common/entity/TransactionSummary.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
Labels: ATC

#721 Delete business unit
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BusinessUnitsTableComponent.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/DeleteBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
Labels: ATC

#729 [ATC-07.008.01] Sorting Reports by Size displays entries in ascending and descending order by size
  src/test/java/xyz/npgw/test/page/common/table/ReportsTableComponent.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
Labels: Reports, ATC

#741 [ATC_06.018.03] Verify, the Transaction detail dialog is closed after clicking on 'x' button"add testCloseXIcon
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: ATC

#744 [ATC_10.010.01] Verify that company cannot be deleted if there are associated business units [ATC_10.010.02] Verify that company cannot be deleted if there are users assigned to it
  src/test/java/xyz/npgw/test/run/CompaniesAndBusinessUnitsTest.java
Labels: System / Companies and BU

#751 Refactor after update 13.06
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/CompaniesAndBusinessUnitsTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
Labels: Refactoring

#754 [ATC_06.018.04] Verify, the data in Transaction Details Dialog correspond to the data in Transactions tableadd testDataMatchingNew
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/page/dialog/TransactionDetailsDialog.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: ATC

#755 Feature/dockerize
  docker/Dockerfile
  pom.xml
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/run/Run.java
Labels: Feature

#777 Add API wait
  src/test/java/xyz/npgw/test/common/entity/Company.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring

#776 Refactor Add BU
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/CompaniesAndBusinessUnitsTest.java
Labels: System / Companies and BU

#784 Fix transaction tests
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring

#785 Bring tests online again
  src/test/java/xyz/npgw/test/common/entity/Acquirer.java
  src/test/java/xyz/npgw/test/common/entity/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/entity/MerchantAcquirer.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/common/SelectDateRangeComponent.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
Labels: Refactoring

#786 Bring tests back online
  src/test/java/xyz/npgw/test/common/entity/App.java
  src/test/java/xyz/npgw/test/common/entity/Info.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/SelectDateRangeComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectStatusComponent.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
Labels: Refactoring

#779 Refactoring testCheckTransactionDetails
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/page/dialog/TransactionDetailsDialog.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring

#792 Fix dashboard summary tests
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/common/SelectDateRangeComponent.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Fix

#793 Refactor after 0.1.2506220958
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/entity/Acquirer.java
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/common/MenuComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/UserTableComponent.java
  src/test/java/xyz/npgw/test/page/dialog/TransactionDetailsDialog.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
Labels: Refactoring

#796 Fix retry compatibility
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Fix

#795 [ATC-10.008.06] Editing a business unit updates its name while preserving the same ID
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/BusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/EditBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: System / Companies and BU

#797 Edit testFilterAcquirersByStatus
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: System / Acquirers

#817 Refactor transaction tests
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
Labels: Refactoring, Transactions/Details

#807 Select Acquirer GatewayPage
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AddMerchantAcquirerDialog.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsTableTest.java
Labels: ATC

#812 [ATC_12.001.01] GW > Add active and inactive merchant acquirers
  src/test/java/xyz/npgw/test/page/common/table/GatewayTableComponent.java
  src/test/java/xyz/npgw/test/page/common/trait/GatewayTableTrait.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AddMerchantAcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddMerchantAcquirerDialog.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
Labels: ATC, System / Gateway

#830 [ATC_06.018.05] Transactions details | testPendingOccursAtMostOnceInLifecycle
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/page/dialog/TransactionDetailsDialog.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: ATC, Transactions/Details
