Repository NPGW/npgw-ui-test, pull requests merged in 2025-03, with the labels that each got.

#64 [+] add-log4j logging to framework
  pom.xml
  src/test/java/page/LoginPage.java
  src/test/java/runner/BaseTest.java
  src/test/java/runner/BrowserFactory.java
  src/test/java/runner/PlaywrightOptions.java
  src/test/java/runner/ProjectProperties.java
  src/test/java/runner/ProjectUtils.java
  src/test/resources/log4j2.xml
Labels: enhancement

#70 [!] fix class name typo
  .github/workflows/cancel.yml
  .github/workflows/ci.yml
  .github/workflows/notify.yml
  .gitignore
  README.md
  checkstyle-suppressions.xml
  mod_v10.17.0_google_checks.xml
  pom.xml
  src/test/java/LoginPageTest.java
  src/test/java/runner/BaseTest.java
  src/test/java/runner/PlaywrightOptions.java
  src/test/java/runner/ProjectProperties.java
  src/test/java/runner/ProjectUtils.java
  src/test/resources/allure.properties
  suite/chrome-smoke-parallel.xml
  suite/chrome-smoke.xml
Labels: documentation

#83 [ATC_00.001.00] User email is remembered after first successful login
  src/test/java/LoginPageTest.java
  src/test/java/page/BasePage.java
  src/test/java/page/DashboardPage.java
  src/test/java/page/HomePage.java
  src/test/java/page/LoginPage.java
  src/test/resources/allure.properties
Labels: Login

#84 [ATC_00.001.01] User email is not remembered after first successful login
  src/test/java/LoginPageTest.java
  src/test/java/page/LoginPage.java
Labels: Login

#89 [!] reorder imports & checkstyle
  mod_v10.17.0_google_checks.xml
  src/test/java/xyz/npgw/test/LoginPageTest.java
  src/test/resources/log4j2.xml
Labels: Refactor

#91 [!] locator steps in english
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
Labels: Refactor

#97 Refactor: change CI to use gh-pages
  .github/workflows/ci.yml
Labels: Refactor

#101 Refactor: NullPointerException handling in try-catch for missing properties file
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
Labels: Refactor

#104 Feat: add allure-maven plugin for allure testing
  pom.xml
Labels: Feature update

#131 Add tests
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/tests/TransactionsPageTest.java
Labels: Transactions

#135 Feature: add autologin for all test classes excluding LoginPageTest
  src/test/java/xyz/npgw/test/common/ProjectUtils.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/tests/TransactionsPageTest.java
Labels: Feature update

#138 Refactor: change project structure
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
  suite/chrome-smoke-parallel.xml
  suite/chrome-smoke.xml
Labels: Refactor

#136 Fix: change artefact upload to allure, clean logging and add nullchecks to have a clean allure report
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
Labels: Fix

#142 Fix: gracefully close playwright on unsupported browser
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
Labels: Fix

#146 Refactor: change pages to use header component and move locators
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/SystemAdministrationPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/AuthenticatedPage.java
  src/test/java/xyz/npgw/test/page/base/BasePageWithHeader.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactor

#148 Feature: add playwright request initialized for tests
  src/test/java/xyz/npgw/test/common/PlaywrightOptions.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
Labels: Feature

#152 Feature: add #150 and #151 ATC
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Fix, Feature

#139 ATC_11.000.00 Verify видимость элементов панели управления Acquirers list
  src/test/java/xyz/npgw/test/page/SaAcquirersTab.java
  src/test/java/xyz/npgw/test/page/SystemAdministrationPage.java
  src/test/java/xyz/npgw/test/page/base/BasePage.java
  src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
Labels: Feature

#155 renaming-locator-and-methods SaAcquirersTab
  src/test/java/xyz/npgw/test/page/SaAcquirersTab.java
  src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
Labels: Fix

#147 [Refactor] Add Element for components
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/SystemAdministrationPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/BasePage.java
  src/test/java/xyz/npgw/test/page/base/BasePageWithHeader.java
  src/test/java/xyz/npgw/test/page/component/ContentBlock.java
  src/test/java/xyz/npgw/test/page/component/Element.java
  src/test/java/xyz/npgw/test/page/component/FilterBlock.java
  src/test/java/xyz/npgw/test/page/component/Header.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
  src/test/java/xyz/npgw/test/run/SystemAdministrationPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: enhancement, Feature request, Refactor

#158 ATC 11.000.02 Verify: The visibility of the 'Acquirers List' header, which contains a list of Acquirers.
  src/test/java/xyz/npgw/test/page/SaAcquirersTab.java
  src/test/java/xyz/npgw/test/page/base/BasePage.java
  src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
Labels: Administration

#163 fix-refact
  src/test/java/xyz/npgw/test/run/SaAcquirersTabTest.java
Labels: Administration, Fix

#162 Fix: attach artefact code
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
Labels: Fix

#161 Add #160 ATC
  src/test/java/xyz/npgw/test/page/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/SaCompaniesAndBusinessUnitsTab.java
  src/test/java/xyz/npgw/test/page/SystemAdministrationPage.java
  src/test/java/xyz/npgw/test/page/component/Header.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: SA / Team
