Repository NPGW/npgw-ui-test, pull requests merged in 2025-05, with the labels that each got.

#423 ATC_11.001.04 Ensure that a new Acquirer can be successfully created and appears in the Acquirers list.
  src/test/java/xyz/npgw/test/common/TestUtils.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AddAcquirerDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
Labels: ATC, System / Acquirers

#425 Fix: rewrite businessUnit & refactor TestUtils
  src/test/java/xyz/npgw/test/common/TestUtils.java
  src/test/java/xyz/npgw/test/common/util/BusinessUnit.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Fix

#428 [ATC_11.001.005 ] SA > Acquirer > Add Acquirer > Attempt to create an Acquirer with an existing name
  src/test/java/xyz/npgw/test/common/TestUtils.java
  src/test/java/xyz/npgw/test/common/entity/Acquirer.java
  src/test/java/xyz/npgw/test/common/entity/SystemConfig.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AddAcquirerDialog.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
Labels: ATC, System / Acquirers

#426 Fix: rm ignore testAddCompanyEndToEndTest
  src/test/java/xyz/npgw/test/common/entity/Address.java
  src/test/java/xyz/npgw/test/common/entity/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/entity/Company.java
  src/test/java/xyz/npgw/test/common/entity/SystemConfig.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/Company.java
  src/test/java/xyz/npgw/test/common/util/Merchant.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Fix

#429 Fix ignored tests in AddCompanyTest
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: Refactoring, System / Companies and BU

#431 Fixing TeamPageTest
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#441 [ATC_01.006.02], [ATC_01.006.03] Verify that the user can switch the color theme
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
Labels: ATC, Header

#433 ATC_11.000.08 Verify Acquirers table contains correct column headers
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/MenuComponent.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: ATC, System / Acquirers

#445 Transactions -> testFilterTransactionsByCurrency fixing after update #444
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, Fix

#446 fix [ATC_01.006.02], [ATC_01.006.03] Verify that the user can switch the color theme
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/run/HeaderComponentTest.java
Labels: Fix, Header

#449 Removed Ignore
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
Labels: Fix

#453 System -> Team -> Create new company admin user
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java
  src/test/java/xyz/npgw/test/page/system/MenuComponent.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: System / Team, ATC

#455 Framework -> ResponseUtils -> add methods
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AddAcquirerDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/MenuComponent.java
Labels: Bug:ATC or framework

#459 AddBusinessUnitTest - fix ignored tests
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
Labels: Fix, System / Companies and BU

#467 fix EditBusinessUnitDialogTest after update
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
Labels: Fix, System / Companies and BU

#461 Fix ATC_11.006.00 Was ignored after updating
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
Labels: Fix, ATC, System / Acquirers

#464 Fix ignored tests
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java
  src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: System / Team, Fix, System / Companies and BU

#468 Feature: handle token expiration
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
Labels: Feature

#424 RF: [ATC_10.008.00] changed dialog title
  src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Fix, System / Companies and BU

#473 [ATC_09.007.03] [ATC_09.007.04][ATC_09.007.05] Edit company admin
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/base/BaseModel.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/page/common/TableTrait.java
  src/test/java/xyz/npgw/test/page/dialog/user/ChangeUserActivityDialog.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: ATC

#470 ATC_11.002.01 Verifies that the Acquirers table displays correct data for the selected acquirer and shows relevant action buttons.
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
Labels: ATC, System / Acquirers

#469 fix ignored testFilterTransactionsByAmount
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, System / Team, Fix

#488 [ATC_06.006.01] Download files: PDF, Excel, CVS
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#486 Refactor alert with AlertTrait и AlertComponent
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/common/AlertComponent.java
  src/test/java/xyz/npgw/test/page/common/AlertTrait.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyTrait.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#493 [ATC_09.007.06]Create company analyst test
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java
  src/test/java/xyz/npgw/test/page/system/UserTableComponent.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: ATC

#489 Add ATC_11.000.09 Verifies that table column headers are displayed correctly on each page when navigating through paginated results.
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Visual, ATC, System / Acquirers

#480 A small test for reset filter on Companies and Business Unit
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitComponent.java
  src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
Labels: ATC, System / Companies and BU

#500 Cleaning Test testColumnHeadersDisplayCorrectlyOnAllPages
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: Refactoring, System / Acquirers

#499 Feature: add test run failFast
  .github/workflows/ci.yml
  config/testng.xml
  pom.xml
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/base/RetryAnalyzer.java
  src/test/java/xyz/npgw/test/common/base/RetryListener.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/AlertComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitTrait.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Feature

#504 Refactor to test fail first behavior
  .github/workflows/ci.yml
  src/test/java/xyz/npgw/test/common/Constants.java
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/base/RetryListener.java
  src/test/java/xyz/npgw/test/common/entity/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/util/ResponseUtils.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/common/AlertComponent.java
  src/test/java/xyz/npgw/test/page/common/DateRangePickerTrait.java
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/page/dialog/user/ChangeUserActivityDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/MenuComponent.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#505 Make constants, remove repeating methods
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#507 Fix create acquirer
  src/test/java/xyz/npgw/test/common/entity/SystemConfig.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
Labels: Fix

#510 [ATC_07.004.00] Reports -> Generate report -> Verify content of 'Generation Parameters dialog'
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/page/dialog/reports/ReportsParametersDialog.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
Labels: Reports, ATC

#506 Add do cycle in test
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: Refactoring, System / Acquirers

#511 Refactor after cleanup
  config/testng.xml
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#512 [ATC_07.004.01] Reports -> Generate report -> Check/uncheck reports columns in the 'Generation Parameters dialog'
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/dialog/reports/ReportsParametersDialog.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
Labels: Reports, ATC

#514 Add Acquirer Component
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/SelectAcquirerComponent.java
  src/test/java/xyz/npgw/test/page/system/SelectAcquirerTrait.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
Labels: Refactoring

#513 [ATC_10.008.02] System administration > Companies and business units > Edit BU | Verify that the label of each field is correct
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: ATC, System / Companies and BU

#519 Remove duplicating tests
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: Refactoring

#520 [ATC_06.001.00] Verify that the Company admin can see all the company's business units in the Business unit dropdown list
  src/test/java/xyz/npgw/test/page/common/SelectBusinessUnitComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#527 ATC_11.001.07 Verify that 'Create' button is disabled when Acquirer name is empty.
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: ATC

#517 [ATC_10.008.01]System administration > Companies and business units >Edit BU | Verify that company name is pre-filled correctly and read-only
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/BusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/EditBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: ATC, System / Companies and BU

#529 [ATC_10.008.03] System administration > Companies and business units > Edit BU | Verify that the dialog is closed by clicking on the 'Close' button
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: ATC, System / Companies and BU

#530 RF: changed merchant -> business unit in allure annotations (addBusinessUnitTest)
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
Labels: Refactoring, System / Companies and BU

#532 [ATC-09.001.01] Team | Status filter correctly displays users with 'Active' or 'Inactive' status
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/page/system/UserTableComponent.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: System / Team, ATC

#535 Delete repeating methods
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/page/system/UserTableComponent.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#545 [ATC_10.008.04] System administration > Companies and business units > Edit BU | Verify that the dialog is closed by clicking on the 'Close' icon
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: ATC, System / Companies and BU

#555 Refactor testCreateCompanyAnalystAndDeactivate
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: ATC

#548 ATC_11.001.06 Verify validation messages when creating Acquirer with invalid input
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
Labels: ATC, System / Acquirers

#558 ATC_11.000.10 Verify that Acquirer with status 'Active/Inactive' is displayed correctly in the list
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/page/system/UserTableComponent.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
Labels: ATC, System / Acquirers

#556 Refactor AddUserDialog methods for TeamPageTest
  src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: System / Team, Refactoring

#541 [ATC_01.006.05] Check validation error messages when changing pas…
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: ATC, Header

#573 Refactor after update branch
  src/test/java/xyz/npgw/test/common/entity/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring

#574 Refactor AddBusinessUnitTest
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
Labels: Refactoring

#580 Refactor AddCompanyDialogTest
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
Labels: Refactoring

#582 Refactor testChangePasswordValidationMessages
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
Labels: Refactoring

#584 Refactoring: table components/traits, packages, naming
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/common/MenuComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectAcquirerComponent.java
  src/test/java/xyz/npgw/test/page/common/TableComponent.java
  src/test/java/xyz/npgw/test/page/common/TableTrait.java
  src/test/java/xyz/npgw/test/page/common/table/AcquirersTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/ReportsTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/UserTableComponent.java
  src/test/java/xyz/npgw/test/page/common/trait/AcquirersTableTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/AlertTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/DateRangePickerTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/HeaderTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/MenuTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/ReportsTableTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/SelectAcquirerTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/SelectBusinessUnitTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/SelectCompanyTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/TransactionsTableTrait.java
  src/test/java/xyz/npgw/test/page/common/trait/UserTableTrait.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/AcquirerDialog.java
  src/test/java/xyz/npgw/test/page/dialog/company/AddCompanyDialog.java
  src/test/java/xyz/npgw/test/page/dialog/merchant/AddBusinessUnitDialog.java
  src/test/java/xyz/npgw/test/page/dialog/reports/ReportsParametersDialog.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/page/system/UserTableTrait.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: System / Team, Refactoring, Fix, System / Acquirers

#581 Refactor EditBusinessUnitDialogTest
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: Refactoring, System / Companies and BU

#583 Refactor TestUtils
  config/checkstyle/mod_v10.17.0_google_checks.xml
  src/test/java/xyz/npgw/test/common/entity/Acquirer.java
  src/test/java/xyz/npgw/test/common/entity/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/entity/Company.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#576 ATC_02.012.00 All key chart elements are correctly displayed
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
Labels: Dashboard

#578 02.005.00 'Reset filter' clears selected options to default
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
Labels: Dashboard

#590 Added asserts due to bug fix
  src/test/java/xyz/npgw/test/page/common/AlertComponent.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#587 Feature cleanup utils
  src/test/java/xyz/npgw/test/common/entity/Acquirer.java
  src/test/java/xyz/npgw/test/common/entity/Company.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/util/CleanupUtils.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Feature

#592 Refactor testChangePassword
  config/checkstyle/mod_v10.17.0_google_checks.xml
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
Labels: Refactoring

#593 Feature: add thread name to console log
  src/test/resources/log4j2.xml
Labels: Feature

#594 Refactor: move userRole to entities
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/entity/UserRole.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/CleanupUtils.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java
  src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Refactoring

#589 Add ATC_11.000.11 Verify Acquirer can be activated and deactivated from the table
  src/test/java/xyz/npgw/test/page/common/SelectAcquirerComponent.java
  src/test/java/xyz/npgw/test/page/common/table/AcquirersTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/UserTableComponent.java
  src/test/java/xyz/npgw/test/page/dialog/acquirer/ChangeAcquirerActivityDialog.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
Labels: ATC, System / Acquirers

#605 Refactoring - remove HeaderComponent
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/common/HeaderComponent.java
  src/test/java/xyz/npgw/test/page/common/trait/HeaderTrait.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring, Bug:ATC or framework

#604 Fix ignored tests
  .github/workflows/ci.yml
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/common/AlertComponent.java
  src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Fix

#601 [ATC_02.013.00] Dashboard transaction summary check
  .github/workflows/ci.yml
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
Labels: ATC

#610 [ATC_02.006.00] Verify merchant ID is sent correctly to the server
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
Labels: ATC

#606 Refactoring -> EditBusinessUnitDialogTest, add BusinessUnitsTableComponent
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/page/common/table/AcquirersTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BusinessUnitsTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/ReportsTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/TransactionsTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/UserTableComponent.java
  src/test/java/xyz/npgw/test/page/common/trait/BusinessUnitsTableTrait.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: Refactoring, System / Companies and BU

#622 [ATC-06.005.00] The request to server contains all the information from the filter
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: ATC

#619 Add ProfileSettingsDialog
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/dialog/BaseDialog.java
  src/test/java/xyz/npgw/test/page/dialog/ProfileSettingsDialog.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
Labels: Project, Refactoring

#613 [ATC-09.002.07] Adding a user with an existing email address results in an error message.
  src/test/java/xyz/npgw/test/page/dialog/user/AddUserDialog.java
  src/test/java/xyz/npgw/test/page/dialog/user/UserDialog.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: System / Team, ATC

#623 Refactoring: Acquirers -> Page/Table
  src/test/java/xyz/npgw/test/page/common/table/AcquirersTableComponent.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
Labels: Refactoring, System / Acquirers

#624 Refactoring: CompaniesAndBU -> Page/Tables
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BusinessUnitsTableComponent.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
Labels: Refactoring, System / Companies and BU

#629 Ignored tests after update
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Bug:ATC or framework

#628 Refactoring: Add SelectStatusComponent
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/SelectStatusComponent.java
  src/test/java/xyz/npgw/test/page/common/trait/SelectStatusTrait.java
  src/test/java/xyz/npgw/test/page/system/AcquirersPage.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/page/system/TeamPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Project, Refactoring

#625 Small changes
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/entity/UserRole.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/common/SelectCompanyComponent.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Fix

#633 Refactoring: TransactionsPage pagination -> component
  src/test/java/xyz/npgw/test/page/TransactionsPage.java
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, Refactoring

#641 Fix getRow() from BaseTableComponent
  src/test/java/xyz/npgw/test/page/common/SelectStatusComponent.java
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
Labels: Fix, Bug:ATC or framework

#642 Refactor after acquirerTitle update
  src/test/java/xyz/npgw/test/common/entity/Acquirer.java
  src/test/java/xyz/npgw/test/common/provider/TestDataProvider.java
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/common/MenuComponent.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Refactoring

#643 Add methods to BaseTableComponent
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/page/system/CompaniesAndBusinessUnitsPage.java
  src/test/java/xyz/npgw/test/run/AcquirersPageTest.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Project, Refactoring, Feature

#634 Improve run separation
  .github/workflows/ci.yml
  src/test/java/xyz/npgw/test/common/ProjectProperties.java
  src/test/java/xyz/npgw/test/common/base/BaseTest.java
  src/test/java/xyz/npgw/test/common/entity/Acquirer.java
  src/test/java/xyz/npgw/test/common/entity/BusinessUnit.java
  src/test/java/xyz/npgw/test/common/entity/Company.java
  src/test/java/xyz/npgw/test/common/entity/User.java
  src/test/java/xyz/npgw/test/common/util/TestUtils.java
  src/test/java/xyz/npgw/test/page/DashboardPage.java
  src/test/java/xyz/npgw/test/page/LoginPage.java
  src/test/java/xyz/npgw/test/page/base/HeaderPage.java
  src/test/java/xyz/npgw/test/page/common/AlertComponent.java
  src/test/java/xyz/npgw/test/page/common/SelectStatusComponent.java
  src/test/java/xyz/npgw/test/page/dialog/ProfileSettingsDialog.java
  src/test/java/xyz/npgw/test/page/dialog/TransactionDetailsDialog.java
  src/test/java/xyz/npgw/test/page/dialog/reports/ReportsParametersDialog.java
  src/test/java/xyz/npgw/test/page/system/BaseSystemPage.java
  src/test/java/xyz/npgw/test/page/system/GatewayPage.java
  src/test/java/xyz/npgw/test/run/AddAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/AddBusinessUnitTest.java
  src/test/java/xyz/npgw/test/run/AddCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/DashboardPageTest.java
  src/test/java/xyz/npgw/test/run/EditAcquirerDialogTest.java
  src/test/java/xyz/npgw/test/run/EditBusinessUnitDialogTest.java
  src/test/java/xyz/npgw/test/run/EditCompanyDialogTest.java
  src/test/java/xyz/npgw/test/run/GatewayPageTest.java
  src/test/java/xyz/npgw/test/run/HeaderTest.java
  src/test/java/xyz/npgw/test/run/LoginPageTest.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
  src/test/java/xyz/npgw/test/run/TeamPageTest.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Fix

#672 Fix allure step
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
Labels: Fix

#674 [ATC-06.003.01] Filtering transactions by Card type displays only matching entries in the table.
  src/test/java/xyz/npgw/test/page/common/table/BaseTableComponent.java
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: Transactions, ATC

#662 [ATC_07.002.00] Reports > Verify that clicking the 'Reset filter' button resets all filters to their default state.
  src/test/java/xyz/npgw/test/page/ReportsPage.java
  src/test/java/xyz/npgw/test/page/common/DateRangePickerComponent.java
  src/test/java/xyz/npgw/test/run/ReportsPageTest.java
Labels: ATC

#669 add [ATC_06.017.08] 'Reset filter' change 'Amount' to default value (…
  src/test/java/xyz/npgw/test/run/TransactionsPageTest.java
Labels: ATC
